FROM alpine:3.9.6

RUN apk update \
    && apk add nginx \
    && mkdir -p /run/nginx

COPY . /usr/share/nginx/html
COPY ./default.conf /etc/nginx/conf.d/

EXPOSE 4000

CMD ["nginx", "-g", "daemon off;"]
